### ISSUE TITLE
Pypi package?

### ISSUE THREAD

**Issue by lucidrains** [Enealor/PyTorch-SM3#15]
Hi! Thank you for building this! Would you be open to publishing this as a Pypi package, so it is pip installable?

**Comment by Enealor** [comment]
Thank you for your interest. I am working on making this into a pip package and sharing it on pypi. I'm trying to have it done by the end of this week.

To explain the wait, I had originally planned on having this included in another optimizer package. However, I have not had time to search for a project to add my work to, and the PyTorch project is interested in keeping their list of included optimizers small. Because of this, offering a package myself is likely the best way to make it easily available.

**Comment by Enealor** [comment]
The package is available on pypi.org at https://pypi.org/project/torch-SM3/. It can be installed using `pip install torch-SM3`. The optimizer can then be imported using `from SM3 import SM3`.
